select * from reservation;

/*TESTING QUEUE*/

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER1','2018-03-18', 8, 'A', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER2','2018-03-18', 9, 'H', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER3','2018-03-18', 10, 'A', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER4','2018-03-18', 11, 'H', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER5','2018-03-18', 12, 'H', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER6','2018-03-18', 13, 'H', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER7','2018-03-18', 14, 'W', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER8','2018-03-18', 15, 'S', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER9','2018-03-18', 16, 'S', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER10','2018-03-18', 17, 'H', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER11','2018-03-18', 18, 'W', 'RESERVED');

INSERT INTO RESERVATION (CUSTOMER_NAME, RESERVATION_DATE, TIME_SLOT, SERVICE_TYPE, DAY_TYPE)
VALUES ('CUSTOMER12','2018-03-18', 19, 'A', 'RESERVED');
