CREATE TABLE `task` (
  `ID_TASK` int(11) NOT NULL AUTO_INCREMENT,
  `DESC_TASK` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DIFFICULTY_LEVEL` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_TASK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `answer` (
  `ID_POSSIBLE` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TASK` int(11) DEFAULT NULL,
  `POSSIBLE_ANSWER` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CORRECT` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID_POSSIBLE`),
  KEY `ID_TASK_FK_idx` (`ID_TASK`),
  CONSTRAINT `ID_TASK_FK` FOREIGN KEY (`ID_TASK`) REFERENCES `task` (`ID_TASK`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `child` (
  `ID_CHILD` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `NUMBER_OF_CORRECT_ANSWERS` int(11) DEFAULT NULL,
  `DURATION_OF_TEST` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_CHILD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


ALTER TABLE `mydb`.`child` 
CHANGE COLUMN `DURATION_OF_TEST` `DURATION_OF_TEST` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL ;

ALTER TABLE `mydb`.`child` 
ADD COLUMN `REACHED_LEVEL` VARCHAR(45) NULL AFTER `DURATION_OF_TEST`;

