INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('5 + 10 = ?', 'LOW');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('7 - 2 = ?', 'LOW');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('16 + 10  - 2 = ?', 'LOW');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('4 * 8 = ?', 'MEDIUM');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('56 / 7 = ?', 'MEDIUM');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES (' 4 * 9 / 6 = ?', 'MEDIUM');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('5 + 13 * 2 = ?', 'HIGH');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('12 - 12 / 2 = ?', 'HIGH');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('5 + 10 * 2 / 4 = ?', 'HIGH');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('100 - 144 / 12 * 8 = ?', 'ADVANCED');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('56 + 324 / 9 - 22 + 7 = ?', 'ADVANCED');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('4 + 963 / 9 + 0 * 256 / 16 = ?', 'ADVANCED');

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (1, 'A: 10', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (1, 'B: 15', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (1, 'C: 18', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (2, 'A: 5', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (2, 'B: 3', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (2, 'C: 4', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (3, 'A: 24', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (3, 'B: 14', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (3, 'C: 34', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (4, 'A: 36', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (4, 'B: 40', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (4, 'C: 32', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (5, 'A: 7', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (5, 'B: 8', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (5, 'C: 6', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (6, 'A: 5', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (6, 'B: 6', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (6, 'C: 4', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (7, 'A: 36', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (7, 'B: 44', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (7, 'C: 31', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (8, 'A: 0', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (8, 'B: 6', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (8, 'C: 1', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (9, 'A: 10', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (9, 'B: 7.5', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (9, 'C: 7', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (10, 'A: -2.3', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (10, 'B: 4', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (10, 'C: -3', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (11, 'A: 62', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (11, 'B: 77', TRUE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (11, 'C: -61', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (12, 'A: 92', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (12, 'B: 3.5', FALSE);

INSERT INTO ANSWER (ID_TASK, POSSIBLE_ANSWER, CORRECT)
VALUES (12, 'C: 111', TRUE);
