INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('5 + 10 = ?', 'LOW');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('7 - 2 = ?', 'LOW');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('16 + 10  - 2 = ?', 'LOW');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('4 * 8 = ?', 'MEDIUM');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('56 / 7 = ?', 'MEDIUM');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES (' 4 * 9 / 6 = ?', 'MEDIUM');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('5 + 13 * 2 = ?', 'HIGH');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('12 - 12 / 2 = ?', 'HIGH');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('5 + 10 * 2 / 4 = ?', 'HIGH');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('100 - 144 / 12 * 8 = ?', 'ADVANCED');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('56 + 324 / 9 - 22 + 7 = ?', 'ADVANCED');

INSERT INTO TASK (DESC_TASK, DIFFICULTY_LEVEL)
VALUES ('4 + 963 / 9 + 0 * 256 / 16 = ?', 'ADVANCED');